---
- name: Python 
  hosts: all
  tasks:
    - name: Install Python support
      apt: "name={{ item }} state=present"
      with_items:
          - python-apt
          - apt-transport-https
          - python-setuptools
          - python-dev 
    - easy_install: name=pip 
    - apt: name=git state=present

- name: Ansible
  hosts: ansible-control 
  tasks:
      - name: Install Ansible 
        pip: name=ansible state=latest

- name: Populate Host File 
  hosts: docker-hosts 
  tasks:
      - name: Copy hostname script to a safe place
        copy: src=scripts/add-host-name.sh dest=/tmp/add-host-name.sh owner=root group=root mode=755 backup=no
      - name: Add nas to hostfile
        command: /tmp/add-host-name.sh nas 192.168.1.234

- name: Docker Containers
  hosts: docker-hosts 
  tasks:
      - name: Create Pull Directory 
        file: path=/opt/git state=directory
      - name: Copy Inventory File 
        copy: src=docker-host.ini dest=/tmp/inventory.ini
      - name: Run Ansible Pull 
        command: /usr/local/bin/ansible-pull --checkout master --directory /opt/ansible-pull --inventory-file=/tmp/inventory.ini --module-name=git --only-if-changed --url=https://github.com/kurron/ansible-pull.git --verbose playbook.yml 
