---
- name: Python 
  hosts: all
  tasks:
    - name: Install Python support
      apt: "name={{ item }} state=present"
      with_items:
          - python-apt
          - apt-transport-https
          - python-setuptools
          - python-dev 
    - easy_install: name=pip 

- name: Docker Daemon
  hosts: all 
  tasks:
      - name: Install Docker keys
        apt_key: state=present keyserver=keyserver.ubuntu.com id=36A1D7869245C8950F966E92D8576A8BA88D21E9
      - name: Install Docker repository
        apt_repository: repo='deb https://get.docker.io/ubuntu docker main' state=present
      - name: Install Docker
        apt: name=lxc-docker state=latest update_cache=true cache_valid_time=600
      - name: Add rkurr to the docker group
        user: name=rkurr state=present groups=docker
      - name: Set Memory and Swap Accounting
        lineinfile: dest=/etc/default/grub regexp='^GRUB_CMDLINE_LINUX=""' line='GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"'
      - name: Rebuild GRUB
        command: update-grub
      - name: Restart Docker
        service: name=docker state=restarted
      - name: Install Docker Compose
        pip: name=docker-compose state=latest

