---
- name: Python 
  hosts: all
  tasks:
    - name: Install Python support
      apt: "name={{ item }} state=present"
      with_items:
          - python-apt
          - apt-transport-https
          - python-setuptools
          - python-dev 
    - easy_install: name=pip 
    - apt: name=git state=present

- name: Ansible
  hosts: ansible-control 
  tasks:
      - name: Install Ansible 
        pip: name=ansible state=latest

- name: Populate Host File 
  hosts: docker-host 
  tasks:
      - name: Copy hostname script to a safe place
        copy: src=scripts/add-host-name.sh dest=/tmp/add-host-name.sh owner=root group=root mode=755 backup=no
      - name: Add nas to hostfile
        command: /tmp/add-host-name.sh nas 192.168.1.234

- name: Set Up Plex Media Server 
  hosts: plex-host 
  tasks:
      - name: Create the NAS mount point 
        file: path=/mnt/nas state=directory
      - name: Install NFS packages 
        apt: name=nfs-common state=present 
      - name: Mount NAS drive 
        mount: fstype=nfs name=/mnt/nas src=nas:/media state=mounted opts=ro

- name: Install Newrelic Server Agent 
  hosts: newrelic-server 
  tasks:
      - apt_repository: repo='deb http://apt.newrelic.com/debian/ newrelic non-free' state=present
      - apt_key: url=https://download.newrelic.com/548C16BF.gpg state=present
      - apt: name=newrelic-sysmond state=present update_cache=yes
      - command: nrsysmond-config --set license_key=9a3465dc990aa65ee1037041a7d0f770ef428cfd 
      - service: name=newrelic-sysmond state=restarted
 
- name: Docker Containers
  hosts: docker-host 
  tasks:
      - name: Create the vagrant group just to work with ansible-pull
        group: name=vagrant state=present
      - name: Create the vagrant user just to work with ansible-pull
        user: name=vagrant group=vagrant  
      - name: Create Pull Directory 
        file: path=/opt/git state=directory
      - name: Copy Inventory File 
        copy: src=docker-host.ini dest=/tmp/inventory.ini
      - name: Run Ansible Pull 
        command: /usr/local/bin/ansible-pull --checkout master --directory /opt/ansible-pull --inventory-file=/tmp/inventory.ini --module-name=git --url=https://github.com/kurron/ansible-pull.git --verbose playbook.yml 
